"""Backward-compatible public core namespace for CGT bandwidth.

The data model is split across focused modules for portability. This module
re-exports the public names that earlier versions exposed from
``cgt_bandwidth.core``.
"""

from .contracts import (
    AtomInstance,
    AtomKey,
    AuditUniverseScope,
    CandidateSpec,
    ComponentFunctional,
    MCVContract,
    ModeDecision,
    ModeTableCertificate,
    ModeTrace,
    ReadCoord,
    ReleaseCertificate,
    ReleaseCheckTable,
    ReleaseEvidencePath,
    RetypingCertificate,
    RowDerivation,
    RowImplicationRule,
    RuleTableCertificate,
    StageCheck,
    StageEvidence,
    StageFailure,
    StoreStepCertificate,
    StoreStepRule,
    StrictConformanceOptions,
    WellFormednessChecker,
    WellFormednessCheckerResult,
    WellFormednessIssue,
    WellFormednessReport,
    WorkBounds,
)
from .finite import (
    MODES,
    STAGE_ORDER,
    Mode,
    Polarity,
    Retention,
    Variance,
    Verdict,
    canonical_pairs,
    freeze_value,
    sorted_unique,
    thaw_value,
)
from .orders import RECH, ClosureStore, Completion, Preorder
from .rows import (
    ActivePresentationLens,
    ConstraintOccurrence,
    EffectProfile,
    EvidenceAtom,
    FiniteRecord,
    Frame,
    ReportLens,
    Row,
    RowSchema,
)
from .spec import BandSpec, ExecutableBandSpec, as_exec_spec

__all__ = [
    "ActivePresentationLens",
    "AtomInstance",
    "AtomKey",
    "AuditUniverseScope",
    "BandSpec",
    "CandidateSpec",
    "ClosureStore",
    "ComponentFunctional",
    "Completion",
    "ConstraintOccurrence",
    "EffectProfile",
    "EvidenceAtom",
    "ExecutableBandSpec",
    "FiniteRecord",
    "Frame",
    "MCVContract",
    "MODES",
    "Mode",
    "ModeDecision",
    "ModeTableCertificate",
    "ModeTrace",
    "Polarity",
    "Preorder",
    "RECH",
    "ReadCoord",
    "ReleaseCertificate",
    "ReleaseCheckTable",
    "ReleaseEvidencePath",
    "RetypingCertificate",
    "RuleTableCertificate",
    "ReportLens",
    "Retention",
    "Row",
    "RowDerivation",
    "RowImplicationRule",
    "RowSchema",
    "STAGE_ORDER",
    "StageCheck",
    "StageEvidence",
    "StageFailure",
    "StoreStepCertificate",
    "StoreStepRule",
    "StrictConformanceOptions",
    "Variance",
    "Verdict",
    "WellFormednessChecker",
    "WellFormednessCheckerResult",
    "WellFormednessIssue",
    "WellFormednessReport",
    "WorkBounds",
    "as_exec_spec",
    "canonical_pairs",
    "freeze_value",
    "sorted_unique",
    "thaw_value",
]
